name: My Frist Github Action
on: [push]
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.13.1'
      - name: Install dependencies
        run: npm install
      - name: Build the project
        run: npm run build
      - name: Setup finish
        run: echo 'Setup success !!!!'
